### PR TITLE
Added some simple async stuff.

### PR DESCRIPTION
**Pull request by JustusAdam**
Parallelized the IO calls.

The four API calls in the controller are now being executed in parallel.

You can see them running in parallel if you set `simple_async.EMIT_NOTIFICATIONS` to `True` before calling the controller.

Output from my terminal:

    17:49:33 Thread GET MEALS has started
    17:49:33 Thread POSTILLON has started
    17:49:33 Thread DEPARTURES has started
    17:49:33 Thread NEWS has started
    17:49:33 Thread NEWS finished
    17:49:33 Thread GET MEALS finished
    17:49:34 Thread POSTILLON finished
    17:49:39 Thread DEPARTURES finished

### CODE REVIEW

**Comment by JustusAdam** [comment]
It is astonishing how much slower the dvb API really is ...

**Comment by h4llow3En** [comment]
Thanks, but please do not do our work. We were just facing the problem of parallelization.

**Comment by JustusAdam** [comment]
There was no issue, how was I supposed to know ... 😣

**Comment by h4llow3En** [comment]
Yes there were no Issues because originally there was just the team of us three who had really good communication. Would you like to join us, @JustusAdam, so we could keep up with the communication to avoid conflicts like this?

**Comment by JustusAdam** [comment]
What do you have? A slack channel?

**Comment by h4llow3En** [comment]
Well we mostly talk in person. :laughing: The rest is discussed a Telegram Group

**Comment by Feliix42** [comment]
@h4llow3En But we can arrange a Slyck group. Or Gitter. Or whatever 😄

**Comment by Feliix42** [comment]
I created a channel, you have been invited. :)

**Pull request merged**
