### PR TITLE
Better code, same semantics. Hopefully more efficient.

### PR DESCRIPTION
**Pull request by JustusAdam**
Untested. The readme never explains how to test ones changes, so I'll be leaving that to the people in charge.

### CODE REVIEW

**Comment by Feliix42** [comment]
Test by running `python3 infoscreen.py`

**Comment by Feliix42** [comment]
This is currently in-dev. We will take care of the readme, when we can be sure that we won't change everything every few minutes.

**Comment by JustusAdam** [comment]
I am now getting errors from the template, is that intended?

**Comment by JustusAdam** [comment]
The ticker doesn't show, is that normal?

**Comment by Feliix42** [comment]
Yes. As I stated above, this is _in-dev_. The template is not finished, and a bulk of functions is not completed. For example, the position of the ticker has not been chosen yet.

**Comment by JustusAdam** [comment]
Well then I think this PR is done testing, it works on my machine :smile_cat:

**Pull request merged**
